- src/data/sorted_items.json
> Added Tirannwn Quiver 3

- src/components/PresetSection/presetSectionApi.ts
This should solve our issues with older version of saved presets having outdated keys. We can change the upload logic later to only store label + breakdownNotes but for right now its not hurting anything to save extra data.
> syncs stored presets to latest local

- src/components/ItemSelectDialogPopup/ItemSelectDialogPopup.css
- src/components/ItemSelectDialogPopup/ItemSelectDialogPopup.tsx
* Set consistent margins around items
* Add tooltip for name on hover
* Remove unnecessary ":" from title
* Clean up CSS class name for image
> enh: improve UI for recent items

- src/data/sorted_familiars.json
> Fix familiar display names

- src/data/sorted_items.json
- src/data/sorted_relics.json
Ring of slaying
Ring of fortune
Ring of wealth
Teleports scrolls:
Bandit camp
Clocktower
Fort Forinthry
Grand Exchange
Gu'Tanoth
Lighthouse
Miscellania
Phoenix lair
Polliniveach
Tai Bwo Wannai
Single menaphos tablet
Single onyx bolt
500 fetch casket scrolls
Standardise familiar scroll names
> Adding clue items + a few other things

- src/data/sorted_familiars.json
- src/data/sorted_items.json
More stuff for abby demon preset and scav farming
> Adding items.json

- src/data/sorted_items.json
Manuscripts, fixing potion names, updating some links
> Adding items

- src/components/PresetActions/PresetActions.tsx
- src/types/saved-preset-data.ts
- src/utility/export-to-png.ts
- src/utility/sanitizer.ts
This will be used by the back-end. It will be converted to a normal PNG and used in SSR for preset previews.
> enh: send base64 preset image to UploadPreset

- package.json
- src/App.tsx
- src/components/PresetEditor/PresetEditor.tsx
- src/components/SlotSection/SlotSection.tsx
- src/redux/store/reducers/preset-reducer.ts
- yarn.lock
This adds drag-and-drop support to the inventory.
> enh: add dnd support

- src/App.css
- src/api/get-preset.ts
- src/api/github.ts
- src/components/BreakdownListItem/BreakdownListItem.tsx
- src/components/HelpDialog/HelpDialog.css
- src/components/HelpDialog/HelpDialog.tsx
- src/components/PresetBreakdown/PresetBreakdown.tsx
- src/data/emoji-settings.ts
- src/main.tsx
- src/utility/emojify.ts
Emojis are loaded from `rotation-builder` on page load.
> enh: add emoji support to notes

- src/components/ItemSelectDialogPopup/ItemSelectDialogPopup.tsx
- src/components/PresetActions/PresetActions.css
- src/components/PresetActions/PresetActions.tsx
Other changes:
* Filter out invalid recent items for the selected slot.
* Styling fixes for preset actions.
> fix: filter out auras from inventory

- src/components/FamiliarSection/FamiliarSection.tsx
- src/components/PresetEditor/PresetEditor.css
- src/components/RelicSection/RelicSection.tsx
- src/components/SlotSection/SlotSection.css
- src/components/SlotSection/SlotSection.tsx
- src/utility/window-utils.ts
This also adds some TODOs for lambdas we need to memoize as well as disabling more functionality on mobile (to make it mostly read-only).
> fix: mobile styling of inventory + relics

- src/components/RelicSection/RelicSection.tsx
- src/components/dialogs/RelicSelectDialogPopup/RelicSelectDialog.tsx
- src/data/sorted_relics.json
- src/types/relic.ts
- yarn.lock
Added simple descriptions for relics on hover, for users that do not know what the relic does.
> Add basic thumbnail description to relics

- src/data/sorted_items.json
> fix typo in enhanced replenishment potion name

- README.md
- src/components/PresetActions/PresetActions.tsx
- src/components/PresetBreakdown/PresetBreakdown.tsx
- src/components/PresetEditor/PresetEditor.css
- src/components/RelicSection/RelicSection.tsx
- src/utility/export-to-png.ts
- vite.config.ts
* docs: add prod URL to readme
* chore: change dev server URL to `localhost` so that imgur requests succeed (127.0.0.1 is blocked)
> enh: hide alternative relics/familiars in PNG exports if theyre empty

- package.json
- src/components/SlotSection/SlotSection.tsx
Other changes:
* chore: add start command to run dev server
> fix: check slot image safely

- src/data/sorted_items.json
-Add Anima core body of Zamorak
-Add Anima core legs of Zamorak
> Update sorted_items.json Add Anima core body and legs of Zamorak

- src/data/sorted_items.json
-Add Seed bag to the preset generator
> Update sorted_items.json Add Seed bag

- src/data/sorted_familiars.json
- src/data/sorted_items.json
-Spirit spider to familiar and pouch
-Bronze full helm, platebody, platelegs, and crossbow
> Add items for NOPENOPENOPE

- src/data/sorted_items.json
-Roar of Awakening
-Ode to Deceit
-Scripture of Amascut
> Update sorted_items.json add Sanctum rewards

- src/data/sorted_items.json
Add the following:
-Underworld Grimoire 4, 
-Pickaxe of Life and Death 
-Masterwork 2h sword
> Update sorted_items.json add Underworld Grimoire 4, Pickaxe of Life and Death, and Masterwork 2h sword

- src/data/sorted_items.json
-Primal abyssal armour spikes (10k)
> Update sorted_items.json add Primal abyssal armour spikes

- src/data/sorted_items.json
-Add superior rock-shell armour
-Add superior skeletal armour
-Add superior spined armour
-Add crystal bow and halberd
-Add off-hand rubber chicken
-Add rope
-Remove my duplicate superior spined gloves
-Fix image link for superior skeletal boots
> Update sorted_items.json add t65 armours, crystal weapons, clue items

- src/data/sorted_items.json
https://github.com/pvme/preset-maker/pull/151
-Roar of Awakening 
-Ode to Deceit 
-Scripture of Amascut
https://github.com/pvme/preset-maker/pull/152
-Underworld Grimoire 4 
-Pickaxe of Life and Death 
-Masterwork 2h sword 
https://github.com/pvme/preset-maker/pull/155
-Ahrim's staff 
-Crystal staff
https://github.com/pvme/preset-maker/pull/156
-Primal abyssal armour spikes (10k) 
https://github.com/pvme/preset-maker/pull/157
-Deathtouched dart 
https://github.com/pvme/preset-maker/pull/161
-Superior rock-shell armour 
-Superior skeletal armour 
-Superior spined armour 
-Crystal bow 
-Crystal halberd
-Off-hand rubber chicken
-Rope
> Update deleted image links from imgur to img.pvme.io

- src/data/sorted_items.json
-Update Cryptbloom armour icons
-Add Primed keris
-Add Consecrated keris
> Update Cryptbloom armour icons, and add Primed keris and Consecrated keris

- src/data/sorted_items.json
- Remove EZK/ABS from EoF
- Replace with base item information
- Add Ring of Retribution
> Update EoFs and add RoR
